version: '3.2'

services:
  pico_cam:
    image: pico_cam:latest
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/rover
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true
