version: '3.2'

services:
  ros_pico:
    image: ros_pico:latest
    build: ./Dockerfile
    volumes:
      - .:/home/rover
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY
      - ROS_IP
    network_mode: "host"
#    ports:
#      - 11311:11311
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true


